# Generated by Django 5.1.2 on 2024-11-14 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smart_fridge',
            fields=[
                ('fridge_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('expire_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_fridge_api.smart_fridge')),
            ],
        ),
    ]
