# Generated by Django 5.1.2 on 2024-11-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_fridge_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fridge",
            fields=[
                ("fridge_id", models.IntegerField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="fridge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="smart_fridge_api.fridge",
            ),
        ),
        migrations.DeleteModel(
            name="Smart_fridge",
        ),
    ]
