# Generated by Django 5.1.2 on 2025-01-27 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_fridge_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='last_charity_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='toCharity',
            field=models.BooleanField(default=False),
        ),
    ]
