# Generated by Django 5.1.2 on 2025-01-27 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_fridge_api', '0002_fridge_last_charity_update_product_tocharity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='last_charity_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
