# Generated by Django 5.1.2 on 2024-11-20 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_fridge_api', '0002_fridge_alter_product_fridge_delete_smart_fridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('sampling_date', models.DateField()),
                ('fridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_fridge_api.fridge')),
            ],
        ),
    ]
