# Generated by Django 5.1.2 on 2024-12-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_fridge_api", "0003_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameters",
            name="sampling_date",
            field=models.DateTimeField(),
        ),
    ]
