# Generated by Django 5.1.2 on 2025-01-27 21:34

import smart_fridge_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_fridge_api', '0003_alter_fridge_last_charity_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='last_charity_update',
            field=models.DateField(default=smart_fridge_api.models.get_today_date),
        ),
    ]
