# Generated by Django 5.1.2 on 2025-01-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_fridge_api', '0004_alter_fridge_last_charity_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='country',
        ),
        migrations.AddField(
            model_name='fridge',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fridge',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
