# Generated by Django 5.1.2 on 2024-12-12 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smart_fridge_api", "0004_alter_parameters_sampling_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Parameters",
            new_name="Parameter",
        ),
    ]
