# Generated by Django 5.1.2 on 2025-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_fridge_api', '0005_remove_fridge_address_remove_fridge_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='last_charity_update',
        ),
        migrations.AddField(
            model_name='fridge',
            name='toCharity_updated_today',
            field=models.BooleanField(default=False),
        ),
    ]
