# Generated by Django 5.1.2 on 2025-01-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_fridge_api', '0006_remove_fridge_last_charity_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='sampling_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
